### ISSUE TITLE
"content_creator_rewards_desc" translate key doesnt work

### ISSUE THREAD

**Issue by WangShayne** [Axentro/axentro-website#8]
![image](https://user-images.githubusercontent.com/17644818/141071482-70802965-1c29-4871-a1a1-bcfa14fcec2d.png)
--- 
![image](https://user-images.githubusercontent.com/17644818/141071580-9a9a8e0b-a850-4c63-868a-c6525b593e23.png)

Because "content_creator_rewards_desc" is under the ul tag of the translate json file,but it's a 'p' tag in html file.
![image](https://user-images.githubusercontent.com/17644818/141072228-259d72e1-2a16-409d-b4e1-c4247d5f675e.png)
![image](https://user-images.githubusercontent.com/17644818/141072301-2cdab46b-18b5-4c95-81ce-9fda5d86463c.png)

**Comment by kingsleyh** [comment]
can you fix this and send a pull request?

**Comment by WangShayne** [comment]
@kingsleyh please review
